{
 "title": "BabyBuddy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Time Since Last Feeding",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(\"start\"),\r\n  extract(epoch from (CURRENT_TIMESTAMP(0)::TIMESTAMP WITH TIME ZONE - \"start\")) as timeSince\r\nFROM\r\n  core_feeding\r\nORDER BY start"
    },
    {
     "rawSql": "SELECT\r\n  $__time(\"start\"),\r\n  CASE\r\n    WHEN extract(epoch from (\"end\" - \"start\")) = 0 THEN '#00FF00'\r\n    ELSE '#e0b400'\r\n  END as duration,\r\n  CASE\r\n    WHEN extract(epoch from (\"end\" - \"start\")) = 0 THEN 0\r\n    ELSE 1\r\n  END as duration_bin\r\nFROM\r\n  core_feeding\r\nORDER BY start"
    }
   ]
  },
  {
   "title": "Time Since Last Pumping or Breast Feeding",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"time\" as timestamp,\r\n  extract(epoch from (CURRENT_TIMESTAMP(0)::TIMESTAMP WITH TIME ZONE - \"time\")) as event\r\nFROM\r\n  core_pumping\r\nUNION\r\nSELECT\r\n  \"start\" as timestamp,\r\n  extract(epoch from (CURRENT_TIMESTAMP(0)::TIMESTAMP WITH TIME ZONE - \"start\")) as event\r\nFROM\r\n  core_feeding\r\nWHERE method IN ( 'both breasts', 'right breast', 'left breast')\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Time Since Last Diaper Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(\"time\"),\r\n  extract(epoch from (CURRENT_TIMESTAMP(0)::TIMESTAMP WITH TIME ZONE - \"time\"))\r\nFROM\r\n  core_diaperchange \r\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Time Since Last Sleep",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(\"start\"),\r\n  extract(epoch from (CURRENT_TIMESTAMP(0)::TIMESTAMP WITH TIME ZONE - \"end\")) as timesince\r\nFROM\r\n  core_sleep\r\nORDER BY start"
    },
    {
     "rawSql": "SELECT\r\n  $__time(\"start\"),\r\n  CASE\r\n    WHEN extract(epoch from (\"end\" - \"start\")) = 0 THEN '#00FF00'\r\n    ELSE '#1F60C4'\r\n  END as duration\r\nFROM\r\n  core_sleep\r\nORDER BY start"
    }
   ]
  },
  {
   "title": "Activity Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  start as timestamp, 'Breast Feeding' as feeding\r\nFROM\r\n  core_feeding\r\nWHERE method in ('both breasts', 'left breast', 'right breast')\r\nGROUP BY timestamp\r\nUNION\r\nSELECT\r\n  start as timestamp, 'Bottle Feeding' as feeding\r\nFROM\r\n  core_feeding\r\nWHERE method in ('bottle')\r\nGROUP BY timestamp\r\nUNION\r\nSELECT\r\n  \"end\" as timestamp, 'None' as feeding\r\nFROM\r\n  core_feeding\r\nGROUP BY timestamp\r\n"
    },
    {
     "rawSql": "SELECT\r\n  \"time\" as timestamp, 'Wet Diaper' as diaper\r\nFROM\r\n  core_diaperchange\r\nWHERE wet is TRUE AND solid is FALSE \r\nGROUP BY timestamp\r\nUNION\r\nSELECT\r\n  \"time\" as timestamp, 'Solid Diaper' as diaper\r\nFROM\r\n  core_diaperchange\r\nWHERE wet is FALSE AND solid is TRUE \r\nGROUP BY timestamp\r\nUNION\r\nSELECT\r\n  \"time\" as timestamp, 'Wet/Solid Diaper' as diaper\r\nFROM\r\n  core_diaperchange\r\nWHERE wet is TRUE AND solid is TRUE \r\nGROUP BY timestamp\r\nUNION\r\nSELECT\r\n  \"time\" + INTERVAL '10 min' as timestamp, 'None' as diaper\r\nFROM\r\n  core_diaperchange \r\nGROUP BY timestamp"
    },
    {
     "rawSql": "SELECT\r\n  \"time\" as timestamp, 'Pumping' as pumping\r\nFROM\r\n  core_pumping\r\nGROUP BY timestamp\r\nUNION\r\nSELECT\r\n  \"time\" + INTERVAL '45 min' as timestamp, 'None' as pumping\r\nFROM\r\n  core_pumping\r\nGROUP BY timestamp"
    },
    {
     "rawSql": "SELECT\r\n  start as timestamp, 'Napping' as sleeping\r\nFROM\r\n  core_sleep\r\nWHERE napping is TRUE\r\nGROUP BY timestamp\r\nUNION\r\nSELECT\r\n  start as timestamp, 'Sleeping' as sleeping\r\nFROM\r\n  core_sleep\r\nWHERE napping is FALSE\r\nGROUP BY timestamp\r\nUNION\r\nSELECT\r\n  \"end\" as timestamp, 'None' as sleeping\r\nFROM\r\n  core_sleep\r\nGROUP BY timestamp\r\n"
    }
   ]
  },
  {
   "title": "By Hour Averages, Trailing Two Weeks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Average Amount Fed by Hour of Day",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  extract(hour from start) as hour,\r\n  avg(amount) as avgAmount\r\nFROM\r\n  core_feeding\r\nWHERE start > CURRENT_TIMESTAMP(0)::TIMESTAMP WITH TIME ZONE - INTERVAL '14 days'\r\nGROUP BY hour\r\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Average Amount Pumped by Hour of Day ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  extract(hour from \"time\") as hour,\r\n  avg(amount) as avgAmount\r\nFROM\r\n  core_pumping\r\nWHERE \"time\" > CURRENT_TIMESTAMP(0)::TIMESTAMP WITH TIME ZONE - INTERVAL '14 days'\r\nGROUP BY hour\r\nORDER BY hour"
    }
   ]
  },
  {
   "title": "Average Nap Duration by Hour of Day",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  extract(hour from start) as hour,\r\n  extract(epoch from avg(duration))*1000 as avgDuration\r\nFROM\r\n  core_feeding\r\nWHERE start > CURRENT_TIMESTAMP(0)::TIMESTAMP WITH TIME ZONE - INTERVAL '14 days'\r\nGROUP BY hour\r\nORDER BY hour"
    }
   ]
  },
  {
   "title": "By Hour Averages, All Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Amount Fed by Hour of Day",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  extract(hour from start) as hour,\r\n  avg(amount) as avgAmount\r\nFROM\r\n  core_feeding\r\nGROUP BY hour\r\nORDER BY hour"
      }
     ]
    },
    {
     "title": "Average Amount Pumped by Hour of Day ",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  extract(hour from \"time\") as hour,\r\n  avg(amount) as avgAmount\r\nFROM\r\n  core_pumping\r\nGROUP BY hour\r\nORDER BY hour"
      }
     ]
    },
    {
     "title": "Average Nap Duration by Hour of Day",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  extract(hour from start) as hour,\r\n  extract(epoch from avg(duration))*1000 as avgDuration\r\nFROM\r\n  core_feeding\r\nGROUP BY hour\r\nORDER BY hour"
      }
     ]
    }
   ]
  },
  { "title": "More Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Heatmap of Feeding Modes",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "with t as\r\n(\r\nSELECT\r\n  \"start\",\r\n  \"type\", \r\n  CASE\r\n    WHEN method = 'left breast' THEN 'breasts'\r\n    WHEN method = 'right breast' THEN 'breasts'\r\n    WHEN method = 'both breasts' THEN 'breasts'\r\n\tELSE method\r\n  END AS method\r\nFROM\r\n  core_feeding\r\n)\r\n\r\nSELECT\r\n  \"type\", \r\n  \"method\",\r\n  count(*)\r\nFROM\r\n  t\r\nGROUP BY \"type\", \"method\""
    }
   ]
  }
 ]
}